// <auto-generated />
using EsercizioAuto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsercizioAuto.Migrations
{
    [DbContext(typeof(AutoContext))]
    [Migration("20221021160950_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("EsercizioAuto.Model.Assicurazione", b =>
                {
                    b.Property<int>("AssicurazioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sede")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssicurazioneId");

                    b.ToTable("Assicurazione");
                });

            modelBuilder.Entity("EsercizioAuto.Model.Auto", b =>
                {
                    b.Property<string>("Targa")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssicurazioneId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cilindrata")
                        .HasColumnType("REAL");

                    b.Property<double>("Potenza")
                        .HasColumnType("REAL");

                    b.Property<int>("ProprietarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Targa");

                    b.HasIndex("AssicurazioneId");

                    b.HasIndex("ProprietarioId");

                    b.ToTable("Auto");
                });

            modelBuilder.Entity("EsercizioAuto.Model.Proprietario", b =>
                {
                    b.Property<int>("ProprietarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CittàDiResidenza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProprietarioId");

                    b.ToTable("Proprietario");
                });

            modelBuilder.Entity("EsercizioAuto.Model.Auto", b =>
                {
                    b.HasOne("EsercizioAuto.Model.Assicurazione", "Assicurazione")
                        .WithMany("Auto")
                        .HasForeignKey("AssicurazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsercizioAuto.Model.Proprietario", "Proprietario")
                        .WithMany("Auto")
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assicurazione");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("EsercizioAuto.Model.Assicurazione", b =>
                {
                    b.Navigation("Auto");
                });

            modelBuilder.Entity("EsercizioAuto.Model.Proprietario", b =>
                {
                    b.Navigation("Auto");
                });
#pragma warning restore 612, 618
        }
    }
}
