// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _04_TodoApi;

#nullable disable

namespace _04_TodoApi.Migrations
{
    [DbContext(typeof(TodoDb))]
    [Migration("20230427085614_mariadb")]
    partial class mariadb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_04_TodoApi.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsComplete = true,
                            Name = "Pippo"
                        },
                        new
                        {
                            Id = 2,
                            IsComplete = false,
                            Name = "Pluto"
                        },
                        new
                        {
                            Id = 3,
                            IsComplete = true,
                            Name = "Juan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
