// <auto-generated />
using EFCoreImpiegatiDipartimento.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreImpiegatiDipartimento.Migrations
{
    [DbContext(typeof(DipartimentiImpiegatiContext))]
    [Migration("20221011110329_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("EFCoreImpiegatiDipartimento.Model.Dipartimento", b =>
                {
                    b.Property<int>("DipartimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeDip")
                        .HasColumnType("TEXT");

                    b.HasKey("DipartimentoId");

                    b.ToTable("Dipartimenti");
                });

            modelBuilder.Entity("EFCoreImpiegatiDipartimento.Model.Impiegato", b =>
                {
                    b.Property<int>("ImpiegatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .HasColumnType("TEXT");

                    b.Property<int>("DipartimentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<double>("Stipendio")
                        .HasColumnType("REAL");

                    b.HasKey("ImpiegatoId");

                    b.HasIndex("DipartimentoId");

                    b.ToTable("Impiegati");
                });

            modelBuilder.Entity("EFCoreImpiegatiDipartimento.Model.Impiegato", b =>
                {
                    b.HasOne("EFCoreImpiegatiDipartimento.Model.Dipartimento", "Dipartimento")
                        .WithMany("Impiegato")
                        .HasForeignKey("DipartimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dipartimento");
                });

            modelBuilder.Entity("EFCoreImpiegatiDipartimento.Model.Dipartimento", b =>
                {
                    b.Navigation("Impiegato");
                });
#pragma warning restore 612, 618
        }
    }
}
