// <auto-generated />
using EsercizioRistorante.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsercizioRistorante.Migrations
{
    [DbContext(typeof(RistoranteDbContext))]
    [Migration("20230520151644_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EsercizioRistorante.Model.Piatto", b =>
                {
                    b.Property<int>("PiattoId")
                        .HasColumnType("int");

                    b.Property<int>("Costo")
                        .HasColumnType("int");

                    b.Property<string>("NomePiatto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RistoranteId")
                        .HasColumnType("int");

                    b.HasKey("PiattoId");

                    b.ToTable("Piattos");

                    b.HasData(
                        new
                        {
                            PiattoId = 1,
                            Costo = 10,
                            NomePiatto = "piatto 1",
                            RistoranteId = 1
                        },
                        new
                        {
                            PiattoId = 2,
                            Costo = 20,
                            NomePiatto = "piatto 2",
                            RistoranteId = 2
                        },
                        new
                        {
                            PiattoId = 3,
                            Costo = 15,
                            NomePiatto = "piatto 3",
                            RistoranteId = 3
                        });
                });

            modelBuilder.Entity("EsercizioRistorante.Model.Ristorante", b =>
                {
                    b.Property<int>("RistoranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Città")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RistoranteId");

                    b.ToTable("Ristorantes");

                    b.HasData(
                        new
                        {
                            RistoranteId = 1,
                            Città = "milano",
                            Nome = "nome 1"
                        },
                        new
                        {
                            RistoranteId = 2,
                            Città = "roma",
                            Nome = "nome 2"
                        },
                        new
                        {
                            RistoranteId = 3,
                            Città = "napoli",
                            Nome = "nome 3"
                        });
                });

            modelBuilder.Entity("EsercizioRistorante.Model.Piatto", b =>
                {
                    b.HasOne("EsercizioRistorante.Model.Ristorante", "Ristorante")
                        .WithMany("Piattos")
                        .HasForeignKey("PiattoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ristorante");
                });

            modelBuilder.Entity("EsercizioRistorante.Model.Ristorante", b =>
                {
                    b.Navigation("Piattos");
                });
#pragma warning restore 612, 618
        }
    }
}
