// <auto-generated />
using System;
using EsercizioPreVerifica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsercizioPreVerifica.Migrations
{
    [DbContext(typeof(FilmDbContext))]
    partial class FilmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EsercizioPreVerifica.Model.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDiProduzione")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Durata")
                        .HasColumnType("int");

                    b.Property<int>("RegistaId")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FilmId");

                    b.HasIndex("RegistaId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            DataDiProduzione = new DateTime(2023, 5, 13, 9, 42, 21, 462, DateTimeKind.Local).AddTicks(3865),
                            Durata = 180,
                            RegistaId = 1,
                            Titolo = "c"
                        },
                        new
                        {
                            FilmId = 2,
                            DataDiProduzione = new DateTime(2023, 5, 13, 7, 42, 21, 462, DateTimeKind.Utc).AddTicks(3909),
                            Durata = 300,
                            RegistaId = 2,
                            Titolo = "d"
                        },
                        new
                        {
                            FilmId = 3,
                            DataDiProduzione = new DateTime(2023, 5, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Durata = 700,
                            RegistaId = 2,
                            Titolo = "e"
                        },
                        new
                        {
                            FilmId = 4,
                            DataDiProduzione = new DateTime(2023, 5, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Durata = 60,
                            RegistaId = 3,
                            Titolo = "j"
                        });
                });

            modelBuilder.Entity("EsercizioPreVerifica.Model.Regista", b =>
                {
                    b.Property<int>("RegistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nazionalità")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RegistaId");

                    b.ToTable("Registas");

                    b.HasData(
                        new
                        {
                            RegistaId = 1,
                            Cognome = "a",
                            Nazionalità = "IT",
                            Nome = "b"
                        },
                        new
                        {
                            RegistaId = 2,
                            Cognome = "f",
                            Nazionalità = "IT",
                            Nome = "g"
                        },
                        new
                        {
                            RegistaId = 3,
                            Cognome = "h",
                            Nazionalità = "IT",
                            Nome = "i"
                        });
                });

            modelBuilder.Entity("EsercizioPreVerifica.Model.Film", b =>
                {
                    b.HasOne("EsercizioPreVerifica.Model.Regista", "Regista")
                        .WithMany("Films")
                        .HasForeignKey("RegistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regista");
                });

            modelBuilder.Entity("EsercizioPreVerifica.Model.Regista", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
