// <auto-generated />
using System;
using EsercizioVerifica3IA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsercizioVerifica3IA.Migrations
{
    [DbContext(typeof(MotorsportContext))]
    [Migration("20221024151115_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("EsercizioVerifica3IA.Model.Pilota", b =>
                {
                    b.Property<int>("PilotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScuderiaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PilotaId");

                    b.HasIndex("ScuderiaId");

                    b.ToTable("Pilota");
                });

            modelBuilder.Entity("EsercizioVerifica3IA.Model.PuntiPiloti", b =>
                {
                    b.Property<int>("PuntiPilotiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataGara")
                        .HasColumnType("TEXT");

                    b.Property<int>("PilotaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosizioneInGara")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Punti")
                        .HasColumnType("INTEGER");

                    b.HasKey("PuntiPilotiId");

                    b.HasIndex("PilotaId");

                    b.ToTable("PuntiPiloti");
                });

            modelBuilder.Entity("EsercizioVerifica3IA.Model.Scuderia", b =>
                {
                    b.Property<int>("ScuderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazionalità")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeScuderia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ScuderiaId");

                    b.ToTable("Scuderia");
                });

            modelBuilder.Entity("EsercizioVerifica3IA.Model.Pilota", b =>
                {
                    b.HasOne("EsercizioVerifica3IA.Model.Scuderia", "Scuderia")
                        .WithMany("Pilota")
                        .HasForeignKey("ScuderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scuderia");
                });

            modelBuilder.Entity("EsercizioVerifica3IA.Model.PuntiPiloti", b =>
                {
                    b.HasOne("EsercizioVerifica3IA.Model.Pilota", "Pilota")
                        .WithMany("PuntiPiloti")
                        .HasForeignKey("PilotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pilota");
                });

            modelBuilder.Entity("EsercizioVerifica3IA.Model.Pilota", b =>
                {
                    b.Navigation("PuntiPiloti");
                });

            modelBuilder.Entity("EsercizioVerifica3IA.Model.Scuderia", b =>
                {
                    b.Navigation("Pilota");
                });
#pragma warning restore 612, 618
        }
    }
}
