// <auto-generated />
using EsercizioRomanzi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsercizioRomanzi.Migrations
{
    [DbContext(typeof(RomanziContext))]
    [Migration("20221018112429_init1")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("EsercizioRomanzi.Model.Autore", b =>
                {
                    b.Property<int>("AutoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazionalità")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AutoreId");

                    b.ToTable("Autori");
                });

            modelBuilder.Entity("EsercizioRomanzi.Model.Personaggio", b =>
                {
                    b.Property<int>("PersonaggioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RomanzoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonaggioId");

                    b.HasIndex("RomanzoId");

                    b.ToTable("Personaggi");
                });

            modelBuilder.Entity("EsercizioRomanzi.Model.Romanzo", b =>
                {
                    b.Property<int>("RomanzoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnnoPubblicazione")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RomanzoId");

                    b.HasIndex("AutoreId");

                    b.ToTable("Romanzi");
                });

            modelBuilder.Entity("EsercizioRomanzi.Model.Personaggio", b =>
                {
                    b.HasOne("EsercizioRomanzi.Model.Romanzo", "Romanzo")
                        .WithMany("Personaggio")
                        .HasForeignKey("RomanzoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Romanzo");
                });

            modelBuilder.Entity("EsercizioRomanzi.Model.Romanzo", b =>
                {
                    b.HasOne("EsercizioRomanzi.Model.Autore", "Autore")
                        .WithMany("Romanzo")
                        .HasForeignKey("AutoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autore");
                });

            modelBuilder.Entity("EsercizioRomanzi.Model.Autore", b =>
                {
                    b.Navigation("Romanzo");
                });

            modelBuilder.Entity("EsercizioRomanzi.Model.Romanzo", b =>
                {
                    b.Navigation("Personaggio");
                });
#pragma warning restore 612, 618
        }
    }
}
