// <auto-generated />
using System;
using EsempiModel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsempiModel.Migrations
{
    [DbContext(typeof(Car1Context))]
    [Migration("20221017093226_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("EsempiModel.Model.Car1", b =>
                {
                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("State", "LicensePlate");

                    b.ToTable("Cars1");
                });

            modelBuilder.Entity("EsempiModel.Model.RecordOfSale", b =>
                {
                    b.Property<int>("RecordOfSaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarLicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSold")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("RecordOfSaleId");

                    b.HasIndex("CarState", "CarLicensePlate");

                    b.ToTable("RecordOfSales");
                });

            modelBuilder.Entity("EsempiModel.Model.RecordOfSale", b =>
                {
                    b.HasOne("EsempiModel.Model.Car1", "Car1")
                        .WithMany("SaleHistory")
                        .HasForeignKey("CarState", "CarLicensePlate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car1");
                });

            modelBuilder.Entity("EsempiModel.Model.Car1", b =>
                {
                    b.Navigation("SaleHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
